import { IoCheckmarkSharp } from "react-icons/io5";
const AboutEasyBookingDeatils = () => {
  type Item = {
    title: string;
    details: string;
  };

  const AboutEasyDeatils: Item[] = [
    {
      title: "Best Prices",
      details:
        "Amazing travel experiences are priceless. With a Best Price Guarantee on all tours, you always get the best deal.",
    },
    {
      title: "Wide Selection of Tours",
      details:
        "Offering tours in 130+ countries and on all continents, allows you to easily find and book your favourite day tours and package tours.",
    },
    {
      title: "Qualified Tour Operators",
      details:
        "We insist on a very high tour quality and therefore only work with qualified and professional tour companies.",
    },
    {
      title: "Professional Tour Guide",
      details:
        "For all tours, you can make an enquiry directly with the tour operator, and get a customised tour offer.",
    },
    {
      title: "Fast Booking",
      details:
        "Zourney is automatically offsetting the carbon footprint generated by all tour bookings, for online package tour booking platforms.",
    },
    {
      title: "Pesonalized Trips",
      details:
        "Our local travel experts will design a trip that matches your unique interests and special requirements, booking everything.",
    },
  ];
  return (
    <div className="my-24  about-easy-booking-deatils-img ">
      <div className="max-w-7xl mx-auto pb-12">
        <div className="text-center">
          <p className="text-sm pb-9 pt-9 uppercase text-black font-[400]">
            Why Book With Us
          </p>
          <h2 className="text-5xl font-bold text-black ">
            Convenient and Easy Tour <br /> Booking Process{" "}
          </h2>
          <div className="w-[100px] h-[1px] bg-[#E46D30] mx-auto my-12"></div>
        </div>
        <div className="grid lg:grid-cols-3 sm:grid-cols-1 gap-5 gap-y-12 ">
          {AboutEasyDeatils.map((i, index) => (
            <div className="px-6" key={index}>
              <div className="flex items-center">
                <IoCheckmarkSharp className="text-[#8E8A46] text-xl " />
                <h2 className="text-2xl font-bold ml-4">{i.title}</h2>
              </div>
              <p className="text-[16px] font-medium text-[#5c626a] mt-5">
                {i.details}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default AboutEasyBookingDeatils;
